INSERT INTO tags (message)
VALUES ('arms workout'),
       ('arms & chest'),
       ('back'),
       ('biceps'),
       ('buttocks'),
       ('calves'),
       ('cardio'),
       ('chest'),
       ('crossfit workout'),
       ('chest&back'),
       ('legs'),
       ('lightweight'),
       ('press'),
       ('press & legs'),
       ('quadriceps'),
       ('shoulders'),
       ('stretching'),
       ('triceps');